### PR TITLE
Feature: dataloader choose complex geometry

### PR DESCRIPTION
**Pull request by tiaguinho-code**
Now you can choose your geometry in the dataloader

### CODE REVIEW

**Review by mlederbauer — CHANGES_REQUESTED** [review]
What exactly does this complex_geoemtry paraeter do? (I only see two lines chhnaged in the code)
Shouldn’t it filter then according to

`df = df[df[‘geometry’]==self.complex_geometry]`

at the same time, we need to also allow the case where we have multiple geometries.

Let’s keep it simple for now and only keep the octahedral complexes hardcoded, what do you think?

i.e., adding after load_dataset_from_hf() in load_data() this filter statement

**Comment by tiaguinho-code** [comment]
I'm not sure what you mean. There are these lines here in the code

**Comment by mlederbauer** [comment]
I see, sorry about the confusion. I didn't see the changed lines of code somehow🤔 Thanks for the addition and ready to merge IMO:) I'll merge it in a bit once Im at the computer!

**Review by mlederbauer — APPROVED** [review]
Thanks!

**Pull request merged**
