### PR TITLE
Tests: Added some tests for the dataloader

### LINKED ISSUE #36: fix(DataLoader): fix one-hot encoding and implement tests for multiple cases -- metal as target, other metals, ...
Also add a bit of documentations of "how to run tests" so that one can mitigate this earlier on in the development

### PR DESCRIPTION
**Pull request by tiaguinho-code**
## Dataloader Tests
Tests check if the output arrays are correct and if some errors are raised when wrong inputs are given to the dataloader.
## Dataloader Speedup
Added manual caching of Dataset locally so it's way quicker when loading.
## Function Descriptions
Cleaned them up a bit and expanded

### CODE REVIEW

**Comment by tiaguinho-code** [comment]
Anyone have any ideas how to make the dataset available to the tests?
Maybe we can give it a fake dataset or something or a shortened version. @mlederbauer what do you think?

**Comment by mlederbauer** [comment]
HI Tiago! Many thanks for looking into this! We could provide a “dummy dataset” of the first 3 lines of the real dataset, and provide the model with this. I’ll take a look and contribute to the branch if I find it

**Comment by mlederbauer** [comment]
The error stems likely from the fact that one needs to be authenticated to access the dataset, the “test entity” is not an authenticated user. A dummy dataset, as you say, would be the best approach here

**Comment by tiaguinho-code** [comment]
Yeah, I was thinking about passing one of my keys to the hfrepo but I guess the data is sensitive enough that this shouldn't be done. I will do something with a dummy dataset.

**Comment by mlederbauer** [comment]
Okay; this is weird, as the tests pass locally when running `make test`, but not on the github workflow here (it’s already a very good sign, but let’s aim to get the green checkmark on Github as well)

**Comment by tiaguinho-code** [comment]
Don't worry, its very expected as the dataloader has a function that loads from huggingface and that is dependent on having completed the login to huggingface. As this is not possible, as the test suite kinda sets up its own environment without access to the login token, it won't be able to get the dataset to do the tests. To circumvent this, assuming the dataset won't change, I implemented a test flag to the dataloader, so it loads a dummy test-set with only 5 rows of the original and it doesn't need to access huggingface. Also added this dummy test-set to the public repo.

**Review by mlederbauer — APPROVED** [review]
Thank you, Tiago, super well documented and a very valuable addition to the codebase! Ready to merge imo

**Comment by mlederbauer** [comment]
Is it ready to create a PR and merge? @tiaguinho-code

**Comment by tiaguinho-code** [comment]
@mlederbauer was thinking about adding some more tests first, but in principle it already works

**Comment by mlederbauer** [comment]
Okay perfect, thank you! Let me know if there’s anything to review or discuss!

**Comment by tiaguinho-code** [comment]
Ran out of ideas for tests, if the dataloader breaks these will definetly fail.

**Pull request merged**
