### PR TITLE
Feat/3 data loader: Implement DataLoader Class in dataset.py

### LINKED ISSUE #3: Data: build dataloader for creating categorical data from input df
Why do we need it?: to start building ML models in the first place
When do we need it?: as soon as possible to start building ML models
Who should do it?: this is a good practice to learn how to transform a dataset into a categorical dataset (ligands) and numerical dataset (NMR signals, maybe descriptors). There are a few catches such as train-test leakage that we need to pay attention to. We can also change this "representation" of the data further down the line. The basic script to load the data as a .csv file and extract the ligand "categories" is already implemented in ./nmrcraft/data/
1 person should be on it
-- Data loading from .csv dataset
-- Prepare data for our task: Ligand classification task --> one-hot-encoding of existing ligand library
-- Data cleaning, data scaling
-- Train/Val/Test split

### PR DESCRIPTION
**Pull request by mlederbauer**
Tagging @tiaguinho-code and @strsamue here

This PR introduces the DataLoader class in the dataset.py file. The DataLoader class is a crucial component of our data pipeline, responsible for loading and preprocessing our data.

Changes include:

Added the DataLoader class in dataset.pyThis class will handle the loading and preprocessing of our data.
```python
class DataLoader:
```

The DataLoader class will be further developed to include methods for data loading, preprocessing, and batching. This will allow us to efficiently load and preprocess data for our machine learning models.

Usage:
```python
from nmrcraft.data.dataset import DataLoader

def main(dataset_size, target, model_name):
    ...
    # Create a DataLoader instance
    data_loader = DataLoader()

    # Use the DataLoader instance to load your data
    X_train, X_test, y_train, y_test = data_loader.load_data()
    …
```

Many thanks in advance for adapting or refining the code or reviewing. It gave reproducible results from my end, but you never know, plus there are many things still hard coded!

### CODE REVIEW

**Comment by tiaguinho-code** [comment]
# Dataloader
This dataloader now supports multi target data loading. For example if you pass script.py --target metal it will generate a y where y is the metal encoded. If you pass --target metal_X1_X4_L it will give back a nice 2D array of metal, X1, X4 and L as targets that can be used later when we try to predict various features with our models.

**Review by kbiniek — APPROVED** [review]

**Comment by tiaguinho-code** [comment]
looks like while merging main some stuff broke, will have to look into it again

**Comment by mlederbauer** [comment]
> looks like while merging main some stuff broke, will have to look into it again

Did you face this issue when running `git pull origin main`  and then getting a merge conflict ?

**Comment by tiaguinho-code** [comment]
yeah, I will just redo the megre and overwrite mains dataloader changes

**Comment by tiaguinho-code** [comment]
# Dataloader usage
## Initiate
To initialize the Dataloader here's an example:

```python
        data_loader = DataLoader(
            feature_columns=feature_columns,
            target_columns=args.target,
            dataset_size=args.dataset_size,
        )
        # Load and preprocess data
        X_train, X_test, y_train, y_test = data_loader.load_data()
```
please take a look at all the variables that can be set when initializing the dataloader as you might find something useful for you.
## Target Dimensionality
Now when passing --target argument also multidimensional targets are supported. For example if you pass `--target metal` you will get a target column out of integer encoded metals:

[W, Mo, W] -> **[1, 0, 1]**. 

If you pass multiple targets separated my "_" then you will get a 2D array for example: `--target metal_X3_L`
 
[[W Br THF]        [[1 1 1]
 [W Cl Et2O] ->  [1 0 0]
 [M Cl THF]]        [0 0 1]]

## Splitting
The Class handles splitting so if you want a certain split size ratio just pass it to it.

## Dataset size
Refers to how much of the total dataset gets used -> useful to see with how much data our model can learn.

**Pull request merged**
