### PR TITLE
fix: call baselines.py from reproduce_results.py script

### PR DESCRIPTION
**Pull request by mlederbauer**

### CODE REVIEW

**Comment by mlederbauer** [comment]
Could you kindly select the poster resolution that we need (@kbiniek ), after that we can merge to main. Thanks a lot in advance !!

**Comment by mlederbauer** [comment]
Is this ready to merge @kbiniek @strsamue ?

**Comment by tiaguinho-code** [comment]
Pulled this into #96

**Comment by tiaguinho-code** [comment]
Wait... is this even the right way of doing this? Is closing correct here as there was some  merge stuff?

**Comment by mlederbauer** [comment]
This should be merged into main @tiaguinho-code

**Comment by mlederbauer** [comment]
but I saw that you pulled it into another PR, so we can do that. normally it’s best to graually merge branches into main to keep the commit history tidy:)

**Pull request closed without merging**
