### PR TITLE
One hot encoding and categorical encoding separated in dataloader. Structural featurs implemented.

### PR DESCRIPTION
**Pull request by tiaguinho-code**
# Readdition of One-hot-encoding
Reopening of #35 

# Features:
## One-Hot encoding of the data features
The features of what ligand and what metal are on the complex should be binarized while we keep the NMR info as numbers.
## Binarization of Targets
This PR should add the ability to the dataloader to give out binarized target data.

# Implementation
My current approach is to have a second split and preprocess function because I felt like the two functions would be different enough to justify having two separate ones, but they do share a bit of code. I have no clue how inheritance works in python and if you even can do that stuff with functions or only with classes. If anyone wants to propose a radically different approach to solving this, feel free to suggest it.

# Target example:
image

# New Bugs
A new bug is introduced where you cannot have _all_ the structural features as targets, as that would lead to the X array be empty and the program throwing an Error. I don't think this is something that needs to be quickly fixed, as I believe we will always be leaving out at least one structural feature for the X-array.

### CODE REVIEW

**Comment by mlederbauer** [comment]
Is there a reason you closed the PR @tiaguinho-code ? I think we undid the merge of this branch with main to resolve some errors we had when running different models. We can also merge this branch into main and resolve the bug in a new feature branch — might even be cleaner!

**Comment by mlederbauer** [comment]
You put the work into this feature and we should merge it, but there have been a few bugs. Maybe this is an evaluation problem (likely it is), and we should merge this PR, and resolve the bug with the evaluation in a seprate branch. JHow does this sound to you @kbiniek ?

**Comment by kbiniek** [comment]
The DataLoader per se worked so I agree with @mlederbauer that we readd it (but stick to just loading the metal until the evaluation issue is resolved)

**Comment by tiaguinho-code** [comment]
Alright, then we can merge this one back in :)

**Comment by mlederbauer** [comment]
Thank you @kbiniek @tiaguinho-code

**Comment by mlederbauer** [comment]
In this PR, there are only a few comments removed — is this the one we want? Didn’t you change more in the code? @tiaguinho-code

**Review by mlederbauer — COMMENTED** [review]
In this code, there is only a paragraph deleted, and no code added – is this intentional?

**Comment by tiaguinho-code** [comment]
> In this code, there is only a paragraph deleted, and no code added – is this intentional?

Ideally we could reopen #35, but it seems like that isn't possible as it has already been merged. This little commit was just a small fix I noticed I could do.
The commit history is basically only accessible through reference to #35 afaik

**Pull request closed without merging**
