### PR TITLE
Addition: Add catchphrase with html styling

### PR DESCRIPTION
**Pull request by tiaguinho-code**
- Added a catchphrase for the project with a bit of HTML theming.
- Spaces were inserted by precommit hook

### CODE REVIEW

**Comment by tiaguinho-code** [comment]
Ah, just saw that github does't render the HTML code like my local Markdown preview, I'll see if I can fix this before merge :(

**Review by mlederbauer — COMMENTED** [review]
This is a super cool idea! A pity it’s not able to be diplayed via HTML...
Perhaps we can add this catchphrase to the NMRlogo itself, similar to how it is done in the “real” Minecraft?
image

I was able to add the Minecraftia font locally to use in graphic design programs:
image

Karo @kbiniek created an amazing logo, perhaps we could adapt it with the snall “catchphrase”? Then there’s no need to render the HTML in the README :)

**Comment by tiaguinho-code** [comment]
Sounds like a good idea! Markdown is more focused on plaintext so we would probably need to import it as an image. Considering how short those usually are, we might need to shorten it to something super short like: "Mining into Tensors!" or "Crafting fresh Ligands!" or "From Redstone to NMR!"

**Comment by mlederbauer** [comment]
Yes I absolutely agree! Great ideas. Perhaps we could leave the "plain text" catchphrase in the readme for now and change the logo in the later phases?😃

**Comment by mlederbauer** [comment]
Is it OK like this for now? @tiaguinho-code We'll add the Minecraftia font to the logo at a later stage with the catchphrase(s)🚀

**Review by mlederbauer — APPROVED** [review]

**Pull request merged**
