### PR TITLE
Feat: Added Docker git check and pre commit | Fix: remved useless files

### PR DESCRIPTION
**Pull request by tiaguinho-code**
# Docker

- Added logic to see if the git repos updated or changed on main for Docker to always be up to date. 
- Also added all possible features from the makefile's install to the Docker.
- Added the make package to the archlinux image so you can actually make install inside the docker. [the `@poetry shell` command from the makefile is incompatible with the Docker file as it tries to spawn a shell in a non existing terminal, so leads to the docker image build failing. That's why we can't just make install in the Docker file, however feel free to use make install when working in the image]

# Files
- removed .zshrc and is now in a personal [repo](https://github.com/tiaguinho-code/Archpy_dots) as it's not directly related to the project.
- removed figure.svg as it is a testing remnant that should have never been commited (oopsie)

### CODE REVIEW

**Review by mlederbauer — APPROVED** [review]
Thank you Tiago 🙏 Very cool feature with the automatic updates. Good to merge imo

**Comment by mlederbauer** [comment]
Should we delete the environment.yml then as well? @tiaguinho-code

**Comment by mlederbauer** [comment]
If conda not needed

**Comment by tiaguinho-code** [comment]
> If conda not needed

Yes, if that config file is only for conda then sure. Did you make it yourself or did the script generate that?
As far as I found it's only needed for conda

**Comment by mlederbauer** [comment]
Yes I created that and it is only needed for initiating a conda environment. Not needed if we do not use conda !

**Pull request merged**
