### PR TITLE
feat: core structure of analyhsis scripts

### LINKED ISSUE #19: feat(nmrcraft/plotting and nmrcraft/data): add a PCA for ligand (configuration) space
Best to use descriptors to cluster the ligand classes (or the whole complexes) to show “the extend of covering the chemical space”. We can best use an unsupervised algorithm such as K means clustering or a PCA here

I can take care of it but if anyone else has ideas, you are super welcome to share them or work on the issue too

### PR DESCRIPTION
**Pull request by mlederbauer**
This PR introduces plotting functions to analyze the dataset, to include plots in the report. In particular,

- `scripts/analysis/dataset_statistics.py`: analyze the distribution of categories with bar charts, adapted from semester thesis
- `scripts/analysis/pca_ligand_space.py`: plot a PCA of the ligand space with NMR features only (not with descriptors), adapted from thesis

Run these with `python path/to/script.py`, plots are saved to `plots/`.

Also added a few cosmetic changes to the plotting ftns, such as introducing a setup_style() function to make the custom color scheme very modular.

Let me know if you have any questions or suggestions for feedback! I think @wikicraft , this is most relevant for you rn

### CODE REVIEW

**Comment by mlederbauer** [comment]
Outputs for first script:

image
image

**Comment by mlederbauer** [comment]
PCA output:
image
image
(this is a bit overkill of a plot, way too hard to read the legend):
image

(here separating the "imido" ligands from the "oxo,selenido,sulfido" ligands, and removing the legend)
image
image

I would say it's maybe nicer to plot without a legend? to just show "we explore chemical space".

**Review by tiaguinho-code — APPROVED** [review]
Looks good to merge for me. Maybe others with more artistic finesse might have some suggestions, but on the purely technical side, this code looks good.

**Comment by wikicraft** [comment]
Thank you a lot for the attributes, this figure all looks really nice! I'll add those pca figures into the report today, thank you again!

**Comment by mlederbauer** [comment]
Fantastic, thank you for your feedback! @tiaguinho-code @wikicraft I might polish the figures a bit toward the end of the project, but if the structure per se works, let’s merge and continue with the evaluations. Cheers !

**Pull request merged**
