### PR TITLE
Feat/one hot encoding

### LINKED ISSUE #36: fix(DataLoader): fix one-hot encoding and implement tests for multiple cases -- metal as target, other metals, ...
Also add a bit of documentations of "how to run tests" so that one can mitigate this earlier on in the development

### PR DESCRIPTION
**Pull request by tiaguinho-code**
# Features:
## One-Hot encoding of the data features
The features of what ligand and what metal are on the complex should be binarized while we keep the NMR info as numbers.
## Binarization of Targets
This PR should add the ability to the dataloader to give out binarized target data.

# Implementation
My current approach is to have a second split and preprocess function because I felt like the two functions would be different enough to justify having two separate ones, but they do share a bit of code. I have no clue how inheritance works in python and if you even can do that stuff with functions or only with classes. If anyone wants to propose a radically different approach to solving this, feel free to suggest it.

# Target example:
image

# New Bugs
A new bug is introduced where you cannot have _all_ the structural features as targets, as that would lead to the X array be empty and the program throwing an Error. I don't think this is something that needs to be quickly fixed, as I believe we will always be leaving out at least one structural feature for the X-array.

### CODE REVIEW

**Comment by mlederbauer** [comment]
Thank you Tiago — I’ll take a look as soon as I can (could Sam @strsamue take a look if available?) – I love the screenshot! #NMRcraftFTW

**Comment by tiaguinho-code** [comment]
Currently only the binarization of targets is implemented. One Hot encoding of features is still TODO.
One quirk is, that if a column is already binary, the binarizer just creates a single binary column instead of two.
For example: for W and Mo you'd get a single column array but for Cl, Br, I you get a 3 column array. It should have the same or almost same information density so I think it's fine (or even better as you don't get that weird behavior from the Lecture where two features are equally important/ represent the same thing)

**Comment by tiaguinho-code** [comment]
Added Onehot encoding for structural features and added it to the normalized NMR features

**Comment by strsamue** [comment]
should i review it already @tiaguinho-code or wait since your still working on it?

**Comment by tiaguinho-code** [comment]
> should i review it already @tiaguinho-code or wait since your still working on it?
> 

There's one thing I still want to add and then we can start reviewing.@strsamue

**Comment by tiaguinho-code** [comment]
#TODO add return of the names of targets and features

**Comment by tiaguinho-code** [comment]
Just found a bug that might not be relevant: Currently you cannot have ALL of the structural stuff as predictions as this will throw an error when creating X as it expects at least one feature. This shouldn't be a problem but just to be noted.

**Comment by tiaguinho-code** [comment]
At this point there is logic now for the categorical and binarized dataloader to pass a list of the column names for the y_labels. In case you also need such labels for X let me know.

**Review by kbiniek — APPROVED** [review]

**Pull request merged**
